#!/bin/bash

pacstrap /mnt alsa-utils
pacstrap /mnt apple-t2-audio-config
pacstrap /mnt apple-bcm-firmware
pacstrap /mnt arch-install-scripts
pacstrap /mnt archinstall
pacstrap /mnt base
pacstrap /mnt bind
pacstrap /mnt bolt
pacstrap /mnt brltty
pacstrap /mnt btrfs-progs
pacstrap /mnt clonezilla
pacstrap /mnt cryptsetup
pacstrap /mnt darkhttpd
pacstrap /mnt ddrescue
pacstrap /mnt dhclient
pacstrap /mnt dhcpcd
pacstrap /mnt diffutils
pacstrap /mnt dmidecode
pacstrap /mnt dmraid
pacstrap /mnt dnsmasq
pacstrap /mnt dosfstools
pacstrap /mnt e2fsprogs:e fs
pacstrap /mnt edk2-shell
pacstrap /mnt efibootmgr
pacstrap /mnt espeakup
pacstrap /mnt ethtool
pacstrap /mnt exfatprogs
pacstrap /mnt f2fs-tools
pacstrap /mnt fatresize
pacstrap /mnt fsarchiver
pacstrap /mnt gnu-netcat
pacstrap /mnt gpart
pacstrap /mnt gpm
pacstrap /mnt gptfdisk
pacstrap /mnt grml-zsh-config
pacstrap /mnt grub
pacstrap /mnt hdparm
pacstrap /mnt hyperv
pacstrap /mnt intel-ucode
pacstrap /mnt irssi
pacstrap /mnt iw
pacstrap /mnt iwd
pacstrap /mnt jfsutils
pacstrap /mnt kitty-terminfo
pacstrap /mnt less
pacstrap /mnt lftp
pacstrap /mnt libfido2
pacstrap /mnt libusb-compat
pacstrap /mnt linux-t2
pacstrap /mnt linux-atm
pacstrap /mnt linux-firmware
pacstrap /mnt linux-firmware-marvell
pacstrap /mnt livecd-sounds
pacstrap /mnt lsscsi
pacstrap /mnt lvm2
pacstrap /mnt lynx
pacstrap /mnt man-db
pacstrap /mnt man-pages
pacstrap /mnt mc
pacstrap /mnt mdadm
pacstrap /mnt memtest86+
pacstrap /mnt mkinitcpio
pacstrap /mnt mkinitcpio-archiso
pacstrap /mnt mkinitcpio-nfs-utils
pacstrap /mnt modemmanager
pacstrap /mnt mtools
pacstrap /mnt nano
pacstrap /mnt nbd
pacstrap /mnt ndisc6
pacstrap /mnt nfs-utils
pacstrap /mnt nilfs-utils
pacstrap /mnt nmap
pacstrap /mnt ntfs-3g
pacstrap /mnt nvme-cli
pacstrap /mnt open-iscsi
pacstrap /mnt open-vm-tools
pacstrap /mnt openconnect
pacstrap /mnt openssh
pacstrap /mnt openvpn
pacstrap /mnt partclone
pacstrap /mnt parted
pacstrap /mnt partimage
pacstrap /mnt pcsclite
pacstrap /mnt ppp
pacstrap /mnt pptpclient
pacstrap /mnt pv
pacstrap /mnt python-requests
pacstrap /mnt qemu-guest-agent
pacstrap /mnt refind
pacstrap /mnt reflector
pacstrap /mnt reiserfsprogs
pacstrap /mnt rp-pppoe
pacstrap /mnt rsync
pacstrap /mnt rxvt-unicode-terminfo
pacstrap /mnt screen
pacstrap /mnt sdparm
pacstrap /mnt sg3_utils
pacstrap /mnt smartmontools
pacstrap /mnt sof-firmware
pacstrap /mnt squashfs-tools
pacstrap /mnt sudo
pacstrap /mnt syslinux
pacstrap /mnt systemd-resolvconf
pacstrap /mnt t2fanrd
pacstrap /mnt t2strap
pacstrap /mnt tcpdump
pacstrap /mnt terminus-font
pacstrap /mnt testdisk
pacstrap /mnt tiny-dfr
pacstrap /mnt tmux
pacstrap /mnt tpm2-tss
pacstrap /mnt udftools
pacstrap /mnt usb_modeswitch
pacstrap /mnt usbmuxd
pacstrap /mnt usbutils
pacstrap /mnt vim
pacstrap /mnt virtualbox-guest-utils-nox
pacstrap /mnt vpnc
pacstrap /mnt wireless-regdb
pacstrap /mnt wireless_tools
pacstrap /mnt wpa_supplicant
pacstrap /mnt wvdial
pacstrap /mnt xfsprogs
pacstrap /mnt xl2tpd
pacstrap /mnt zsh
# my additions
pacstrap /mnt neovim
pacstrap /mnt stow
pacstrap /mnt git
pacstrap /mnt linux-t2
pacstrap /mnt linux-t2-headers
pacstrap /mnt unzip
pacstrap /mnt openssh
